Co-Laon/claon-server

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/QUESTION.md, .github/PULL_REQUEST_TEMPLATE.md
=> chore: git and PR template

build.gradle, src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
Set Swagger \#10
- feat: configure Swagger 3
=> feat: configure Swagger3 

src/main/java/coLaon/ClaonBack/application/validator/IdEqualValidator.java, src/main/java/coLaon/ClaonBack/application/validator/IsDeletedValidator.java, src/main/java/coLaon/ClaonBack/application/validator/Validator.java
Validation Model #17 
feat: implement validation model (#17)
=> feat: implement validation model (#17)

build.gradle, src/main/java/coLaon/ClaonBack/common/domain/BaseEntity.java, src/main/java/coLaon/ClaonBack/common/domain/enums/Address.java, src/main/java/coLaon/ClaonBack/common/exception/BadRequestException.java, src/main/java/coLaon/ClaonBack/common/exception/BaseRuntimeException.java, src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java, src/main/java/coLaon/ClaonBack/common/exception/UnauthorizedException.java, src/main/java/coLaon/ClaonBack/common/validator/IdEqualValidator.java, src/main/java/coLaon/ClaonBack/common/validator/IsDeletedValidator.java, src/main/java/coLaon/ClaonBack/common/validator/PasswordFormatValidator.java, src/main/java/coLaon/ClaonBack/common/validator/Validator.java, src/main/java/coLaon/ClaonBack/user/domain/User.java, src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java, src/main/java/coLaon/ClaonBack/user/dto/UserResponseDto.java, src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/AuthController.java, src/main/resources/application-local.yml, src/test/java/coLaon/ClaonBack/ClRaonBackApplicationTests.java
=> feat: sign up for user

CONTRIBUTING.md
- None
fix organization name in CONTRIBUTING.md
=> docs: fix organization name in CONTRIBUTING.md

src/main/java/coLaon/ClaonBack/user/dto/DuplicatedCheckResponseDto.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/AuthController.java
- #13 
implement duplicated check for email and nickname
=> feat: implement duplicated check for email and nickname

build.gradle, src/main/java/coLaon/ClaonBack/ClaonBackApplication.java, src/main/java/coLaon/ClaonBack/common/domain/BaseEntity.java, src/main/java/coLaon/ClaonBack/user/domain/User.java, src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/test/java/coLaon/ClaonBack/AuthServiceTest.java
- #31 
implement test code template with sign up test code
=> feat: implement test code template with sign up test code

src/main/java/coLaon/ClaonBack/laon/Service/LaonService.java, src/main/java/coLaon/ClaonBack/laon/domain/Laon.java, src/main/java/coLaon/ClaonBack/laon/domain/LaonComment.java, src/main/java/coLaon/ClaonBack/laon/domain/LaonLike.java, src/main/java/coLaon/ClaonBack/laon/repository/LaonCommentRepository.java, src/main/java/coLaon/ClaonBack/laon/repository/LaonLikeRepository.java, src/main/java/coLaon/ClaonBack/laon/repository/LaonRepository.java, src/main/java/coLaon/ClaonBack/laon/web/LaonController.java, src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java
- #39 
Add laon and like and comment entity
=> feat: Add laon and like and comment entity

src/main/java/coLaon/ClaonBack/common/domain/BaseEntity.java, src/main/java/coLaon/ClaonBack/common/domain/enums/BasicLocalArea.java, src/main/java/coLaon/ClaonBack/common/domain/enums/MetropolitanArea.java, src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java, src/main/java/coLaon/ClaonBack/laon/Service/LaonService.java, src/main/java/coLaon/ClaonBack/laon/domain/Laon.java, src/main/java/coLaon/ClaonBack/laon/domain/LaonComment.java, src/main/java/coLaon/ClaonBack/laon/domain/LaonLike.java, src/main/java/coLaon/ClaonBack/laon/dto/LikeRequestDto.java, src/main/java/coLaon/ClaonBack/laon/dto/LikeResponseDto.java, src/main/java/coLaon/ClaonBack/laon/web/LaonController.java, src/main/java/coLaon/ClaonBack/user/domain/User.java, src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java, src/main/java/coLaon/ClaonBack/user/web/AuthController.java, src/test/java/coLaon/ClaonBack/AuthServiceTest.java, src/test/java/coLaon/ClaonBack/LaonServiceTest.java
=> feat: create like

.gitignore
- None
add server start script
=> feat: add server start script

.github/PULL_REQUEST_TEMPLATE.md
이슈를 자동으로 닫을 수 있게 PR Template를 변경하였습니다. 
Ref
- https://sundries-in-myidea.tistory.com/90
- https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
- PR 템플릿 수정
=> docs: modify pr template

src/main/java/coLaon/ClaonBack/user/infra/GoogleUserInfoProvider.java, src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java
=> fix: fix bug in oauth login

src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
=> fix: fix bug in sign-in

src/main/java/coLaon/ClaonBack/common/utils/CookieUtil.java
=> fix: fix bug in cookie util

src/main/java/coLaon/ClaonBack/post/dto/ChildCommentResponseDto.java, src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java, src/main/java/coLaon/ClaonBack/post/dto/LikeFindResponseDto.java, src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java, src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/main/java/coLaon/ClaonBack/user/domain/User.java, src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/PostServiceTest.java
=> feat: implement find like

src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java, src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
Fixes #51 
comment view more if child comment > 3
=> refactor: implement comment view more

build.gradle, src/main/java/coLaon/ClaonBack/center/domain/Center.java, src/main/java/coLaon/ClaonBack/center/domain/CenterImg.java, src/main/java/coLaon/ClaonBack/center/domain/CenterImgListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/Charge.java, src/main/java/coLaon/ClaonBack/center/domain/ChargeListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java, src/main/java/coLaon/ClaonBack/center/domain/ObjectListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/OperatingTime.java, src/main/java/coLaon/ClaonBack/center/domain/OperatingTimeListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java, src/main/java/coLaon/ClaonBack/center/domain/SectorInfoListConverter.java, src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java, src/main/java/coLaon/ClaonBack/center/repository/HoldInfoRepository.java, src/main/java/coLaon/ClaonBack/common/utils/CookieUtil.java, src/main/java/coLaon/ClaonBack/common/utils/JwtUtil.java
=> feat: add centor entity

src/main/java/coLaon/ClaonBack/center/domain/Center.java, src/main/java/coLaon/ClaonBack/center/domain/CenterImg.java, src/main/java/coLaon/ClaonBack/center/domain/CenterImgListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/Charge.java, src/main/java/coLaon/ClaonBack/center/domain/ChargeListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java, src/main/java/coLaon/ClaonBack/center/domain/OperatingTime.java, src/main/java/coLaon/ClaonBack/center/domain/OperatingTimeListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java, src/main/java/coLaon/ClaonBack/center/domain/SectorInfoListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/converter/CenterImgListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/converter/ChargeListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/converter/ObjectListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/converter/OperatingTimeListConverter.java, src/main/java/coLaon/ClaonBack/center/domain/converter/SectorInfoListConverter.java, src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java, src/main/java/coLaon/ClaonBack/center/dto/CenterResponseDto.java, src/main/java/coLaon/ClaonBack/center/dto/HoldInfoRequestDto.java, src/main/java/coLaon/ClaonBack/center/dto/HoldInfoResponseDto.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/common/validator/IsAdminValidator.java, src/test/java/coLaon/ClaonBack/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/LaonServiceTest.java, src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
=> feat: add create center

src/main/java/coLaon/ClaonBack/common/GlobalExceptionHandler.java, src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java, src/main/java/coLaon/ClaonBack/common/exception/ExceptionDto.java, src/main/java/coLaon/ClaonBack/common/exception/ServiceUnavailableException.java, src/main/java/coLaon/ClaonBack/common/exception/UnavailableMailServerException.java, src/main/java/coLaon/ClaonBack/common/infrastructure/EmailSender.java
Fixes #104 
add global exception handler
=> feat: add global exception handler

src/main/java/coLaon/ClaonBack/common/domain/Pagination.java, src/main/java/coLaon/ClaonBack/common/domain/PaginationFactory.java, src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java, src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/PostServiceTest.java, src/test/java/coLaon/ClaonBack/UserServiceTest.java
=> feat: add pagination

src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java, src/main/java/coLaon/ClaonBack/user/dto/InstagramResponseDto.java, src/main/java/coLaon/ClaonBack/user/infra/InstagramUserInfoProvider.java, src/main/java/coLaon/ClaonBack/user/service/OAuth2UserInfoProviderSupplier.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/AuthController.java, src/test/java/coLaon/ClaonBack/AuthServiceTest.java
Fixes #98 
add get user info of instagram
=> feat: add get user info of instagram

build.gradle, src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java, src/main/java/coLaon/ClaonBack/common/infrastructure/S3Uploader.java, src/main/java/coLaon/ClaonBack/common/validator/IsImageValidator.java, src/main/java/coLaon/ClaonBack/config/AmazonS3Config.java, src/main/java/coLaon/ClaonBack/storage/domain/enums/Purpose.java, src/main/java/coLaon/ClaonBack/storage/service/StorageService.java, src/main/java/coLaon/ClaonBack/storage/web/StorageController.java, src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
=> feat: s3 setting

src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
Fixes #121 
change view more to comment count
- 
-
=> refactor: refactor comment view more

src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java, src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Fixes #100 
block/unblock user
=> feat:implement block user

src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
resolves #133 
fix count comment which is not deleted
=> fix: fix count comment which is not deleted

src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java, src/main/java/coLaon/ClaonBack/center/repository/HoldInfoRepository.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java, src/main/java/coLaon/ClaonBack/post/domain/ClimbingHistory.java, src/main/java/coLaon/ClaonBack/post/domain/Post.java, src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java, src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java, src/main/java/coLaon/ClaonBack/post/repository/ClimbingHistoryRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Fixes #109 
Fixes #112 
implement find holinfo by center, climbinghistory in post
- 
-
=> feat: implement find holdinfo by center, climbinghistory in post

src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #131 
refactor remove laon when block user
=> refac: refactor remove laon when block user

src/main/java/coLaon/ClaonBack/user/dto/BlockUserFindResponseDto.java, src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java, src/main/java/coLaon/ClaonBack/user/service/LaonService.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #101
feat: implement find block user list
=> feat: implement find block user list (#101)

src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
resolves #111 
search autocomplete 3 center name by keyword
- 
-
=> feat: implement search center name by keyword

src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves #157 
delete guest mode
=> refac: delete guest mode

src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java, src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java, src/main/java/coLaon/ClaonBack/post/repository/ReviewRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/user/domain/User.java, src/main/java/coLaon/ClaonBack/user/service/LaonService.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves #158 
refactor for soft delete
=> refac: refactor for soft delete

src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java, src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java
None
fix bug of all repository
=> fix: fix bug of all repository

src/main/java/coLaon/ClaonBack/common/validator/IsPrivateValidator.java, src/main/java/coLaon/ClaonBack/post/domain/Post.java, src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves #87 
implement find post, refactor postResponseDto
- 
-
=> feat: find post

src/main/java/coLaon/ClaonBack/center/dto/ReviewCreateRequestDto.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/post/repository/ReviewRepository.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
resolves #168 
fix : modify to create multiple reviews for one center
test : implement a failure test for a center where reviews already exist
=> fix : modify to create multiple reviews for one center

src/main/java/coLaon/ClaonBack/center/domain/BookmarkCenter.java, src/main/java/coLaon/ClaonBack/center/dto/BookmarkCenterResponseDto.java, src/main/java/coLaon/ClaonBack/center/repository/BookmarkCenterRepository.java, src/main/java/coLaon/ClaonBack/center/service/BookmarkCenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/test/java/coLaon/ClaonBack/service/BookmarkCenterServiceTest.java
resolves #115 
- feat : implement bookmark center create and delete method (암장 즐겨찾기)
=> feat: implement bookmark center create and delete (#115)

build.gradle, src/main/java/coLaon/ClaonBack/config/QueryDslConfig.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
resolves #41 
add config of querydsl
=> feat: add config of querydsl

src/main/java/coLaon/ClaonBack/common/validator/ClimbingHistorySize.java, src/main/java/coLaon/ClaonBack/common/validator/ClimbingHistorySizeValidator.java, src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java
resolves #167 
add climbing history size validator for create post
=> refac: add climbing history size validator for create post

src/main/java/coLaon/ClaonBack/center/dto/CenterDetailResponseDto.java, src/main/java/coLaon/ClaonBack/center/dto/CenterSearchResponseDto.java, src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java, src/main/java/coLaon/ClaonBack/center/repository/ReviewRepository.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
=> feat: center find

src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
=> refac: refactor for get other user information

src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java, src/main/java/coLaon/ClaonBack/center/dto/CenterBookmarkResponseDto.java, src/main/java/coLaon/ClaonBack/center/repository/CenterBookmarkRepository.java, src/main/java/coLaon/ClaonBack/center/service/CenterBookmarkService.java, src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/main/java/coLaon/ClaonBack/user/service/BlockUserService.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java, src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #issue_number
서비스 로직과 특히 테스트 코드 가독성이 너무 불편하고 현재 service package 통일성이 깨져서 리팩토링
- 
-
=> refac: refactor for service package by domain

src/main/java/coLaon/ClaonBack/common/validator/NotIdEqualValidator.java, src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java, src/main/java/coLaon/ClaonBack/user/domain/Laon.java, src/main/java/coLaon/ClaonBack/user/service/BlockUserService.java, src/main/java/coLaon/ClaonBack/user/service/LaonService.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java, src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #180 
resolves #181 
- 
-
=> fix: fix laon myself and block myself

build.gradle, src/main/java/coLaon/ClaonBack/config/MultipartResolverConfig.java
=> feat: set multipart resolver configuration

src/main/java/coLaon/ClaonBack/center/domain/Center.java, src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java, src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java, src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java, src/main/java/coLaon/ClaonBack/center/dto/CenterBookmarkResponseDto.java, src/main/java/coLaon/ClaonBack/post/domain/ClimbingHistory.java, src/main/java/coLaon/ClaonBack/post/domain/Post.java, src/main/java/coLaon/ClaonBack/post/domain/PostComment.java, src/main/java/coLaon/ClaonBack/post/domain/PostContents.java, src/main/java/coLaon/ClaonBack/post/domain/PostLike.java, src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java, src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/user/domain/User.java, src/test/java/coLaon/ClaonBack/service/AuthServiceTest.java, src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #145 
refactor constructor of domain
=> refac: refactor constructor of domain

src/main/java/coLaon/ClaonBack/center/repository/ReviewRepository.java, src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java, src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/common/domain/PaginationFactory.java, src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java, src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java, src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
resolves #190 
resolves #191 
add querydsl example for post count by center
=> refac: add querydsl example for post and center review

src/main/java/coLaon/ClaonBack/center/service/CenterBookmarkService.java, src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/common/GlobalExceptionHandler.java, src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/user/service/BlockUserService.java, src/main/java/coLaon/ClaonBack/user/service/LaonService.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java, src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves #186 
refactor to appropriate exception according to the error situation
=> refac: refactor to appropriate exception according to the error situation

src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java, src/main/java/coLaon/ClaonBack/version/domain/AppVersion.java, src/main/java/coLaon/ClaonBack/version/dto/AppVersionFindResponseDto.java, src/main/java/coLaon/ClaonBack/version/repository/AppVersionRepository.java, src/main/java/coLaon/ClaonBack/version/service/AppVersionService.java, src/main/java/coLaon/ClaonBack/version/web/AppVersionController.java, src/test/java/coLaon/ClaonBack/repository/AppVersionRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/AppVersionServiceTest.java
resolves #161 
- feat : implement app version confirmation
=> feat: implement app version confirmation (#161)

src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/main/java/coLaon/ClaonBack/post/web/WriterController.java, src/main/java/coLaon/ClaonBack/version/domain/AppStore.java, src/main/java/coLaon/ClaonBack/version/service/AppVersionService.java, src/main/java/coLaon/ClaonBack/version/web/AppVersionController.java, src/test/java/coLaon/ClaonBack/service/AppVersionServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves #192 
fix bug in get user posts about my page
=> fix: fix bug in get user posts about my page

src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java
resolves #200 
fix bug of querydsl subquery
=> fix: fix bug of querydsl subquery

src/main/java/coLaon/ClaonBack/center/domain/CenterImg.java, src/main/java/coLaon/ClaonBack/center/domain/Charge.java, src/main/java/coLaon/ClaonBack/center/domain/OperatingTime.java, src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java, src/main/java/coLaon/ClaonBack/post/domain/Post.java, src/main/java/coLaon/ClaonBack/post/dto/PostUpdateRequestDto.java, src/main/java/coLaon/ClaonBack/post/repository/ClimbingHistoryRepository.java, src/main/java/coLaon/ClaonBack/post/repository/PostContentsRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/test/java/coLaon/ClaonBack/repository/PostContentsRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves #90 
implement post update
=> feat: implement post update

src/main/java/coLaon/ClaonBack/center/domain/Center.java, src/main/java/coLaon/ClaonBack/center/dto/CenterListOption.java, src/main/java/coLaon/ClaonBack/center/dto/CenterPreviewResponseDto.java, src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
resolves #119
암장 정보들을 불러오는 API를 개발합니다. 4가지 옵션 중, 생성날짜 순과 내 북마크 목록을 불러오는 것을 먼저 개발하였습니다. 
-
=> feat: implement center list api

src/main/java/coLaon/ClaonBack/center/domain/Center.java, src/main/java/coLaon/ClaonBack/center/domain/Charge.java, src/main/java/coLaon/ClaonBack/center/domain/ChargeElement.java, src/main/java/coLaon/ClaonBack/center/domain/converter/ChargeListConverter.java, src/main/java/coLaon/ClaonBack/center/dto/CenterBookmarkResponseDto.java, src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java, src/main/java/coLaon/ClaonBack/center/dto/CenterDetailResponseDto.java, src/main/java/coLaon/ClaonBack/center/dto/CenterResponseDto.java, src/main/java/coLaon/ClaonBack/center/dto/ChargeDto.java, src/main/java/coLaon/ClaonBack/center/dto/ChargeElementDto.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostContentsRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #205 
refactor charge list of center
=> refac: refactor charge list of center

src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java, src/test/java/coLaon/ClaonBack/config/QueryDslTestConfig.java, src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
resolves #183 
refactor find all like by post without block user
=> refac: refactor find all like by post without block user

src/main/java/coLaon/ClaonBack/common/domain/PaginationFactory.java, src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java, src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java, src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
resolves #149 
refactor find all comment without block user
=> refac: refactor find all comment without block user

src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java, src/main/java/coLaon/ClaonBack/common/validator/IsHoldValidator.java, src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves #116 
find posts by center with hold info
- 
-
=> feat: find posts by center with hold info

src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java
resolves #204 
refactor center create request dto for null
=> refac: refactor center create request dto for null

src/main/java/coLaon/ClaonBack/center/domain/CenterReport.java, src/main/java/coLaon/ClaonBack/center/domain/CenterReportType.java, src/main/java/coLaon/ClaonBack/center/dto/CenterReportCreateRequestDto.java, src/main/java/coLaon/ClaonBack/center/dto/CenterReportResponseDto.java, src/main/java/coLaon/ClaonBack/center/repository/CenterReportRepository.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
resolves #211 
implement create center report
=> feat: implement create center report

src/main/java/coLaon/ClaonBack/notice/domain/Notice.java, src/main/java/coLaon/ClaonBack/notice/dto/NoticeCreateRequestDto.java, src/main/java/coLaon/ClaonBack/notice/dto/NoticeResponseDto.java, src/main/java/coLaon/ClaonBack/notice/repository/NoticeRepository.java, src/main/java/coLaon/ClaonBack/notice/service/NoticeService.java, src/main/java/coLaon/ClaonBack/notice/web/NoticeController.java, src/test/java/coLaon/ClaonBack/repository/NoticeRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/NoticeServiceTest.java
resolves #210
공지 관련된 API를 개발했습니다. 조회, 생성
- 
-
=> feat: implement notice

src/main/java/coLaon/ClaonBack/post/domain/PostReport.java, src/main/java/coLaon/ClaonBack/post/domain/enums/ReportType.java, src/main/java/coLaon/ClaonBack/post/dto/ReportRequestDto.java, src/main/java/coLaon/ClaonBack/post/dto/ReportResponseDto.java, src/main/java/coLaon/ClaonBack/post/repository/PostReportRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
=> feat: create post report

src/main/java/coLaon/ClaonBack/center/domain/Center.java, src/main/java/coLaon/ClaonBack/center/dto/CenterPreviewResponseDto.java, src/main/java/coLaon/ClaonBack/center/dto/ReviewListFindResponseDto.java, src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java, src/main/java/coLaon/ClaonBack/center/repository/CenterRepositorySupport.java, src/main/java/coLaon/ClaonBack/center/repository/ReviewRepository.java, src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java, src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/ReviewRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
resolves #175 
resolves #203 
fix concurrency bug about rank of center
refac: refactor find center using dynamic query
=> fix: fix concurrency bug about rank of center

src/main/java/coLaon/ClaonBack/center/domain/converter/ChargeListConverter.java
resolves None
fix bug about charge list
=> fix: fix bug about charge list

src/main/java/coLaon/ClaonBack/center/dto/HoldInfoResponseDto.java
resolves #226 
refactor add crayon url for center
=> refac: refactor add crayon url for center

src/main/java/coLaon/ClaonBack/user/domain/User.java, src/main/java/coLaon/ClaonBack/user/dto/IndividualUserResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java, src/main/java/coLaon/ClaonBack/user/dto/UserModifyRequestDto.java, src/main/java/coLaon/ClaonBack/user/dto/UserResponseDto.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/test/java/coLaon/ClaonBack/domain/UserTest.java, src/test/java/coLaon/ClaonBack/repository/BlockUserRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/CenterBookmarkRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/LaonRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/NoticeRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/ReviewRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/UserRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/AuthServiceTest.java, src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java, src/test/java/coLaon/ClaonBack/service/NoticeServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #225 
add body information column of user table
=> refac: add body information column of user table

src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/test/java/coLaon/ClaonBack/service/AuthServiceTest.java
resolves #234
Nickname관련된 필요하지 않은 더블 체크를 삭제합니다.
=> refactor: remove useless nickname check

src/main/java/coLaon/ClaonBack/center/domain/Center.java, src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java, src/main/java/coLaon/ClaonBack/center/domain/CenterReport.java, src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java, src/main/java/coLaon/ClaonBack/post/domain/Post.java, src/main/java/coLaon/ClaonBack/post/domain/PostComment.java, src/main/java/coLaon/ClaonBack/post/domain/PostLike.java, src/main/java/coLaon/ClaonBack/post/domain/PostReport.java, src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java, src/main/java/coLaon/ClaonBack/user/domain/Laon.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #92 
resolves #236 
add to delete user
=> feat: add to delete user

src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java, src/main/java/coLaon/ClaonBack/center/domain/CenterReport.java, src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java, src/main/java/coLaon/ClaonBack/post/domain/Post.java, src/main/java/coLaon/ClaonBack/post/domain/PostComment.java, src/main/java/coLaon/ClaonBack/post/domain/PostLike.java, src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java, src/main/java/coLaon/ClaonBack/user/domain/Laon.java
resolves #239 , #230
cascade 설정이 잘못된 부분을 수정하였습니다.
- 
-
=> fix: cascade error

build.gradle, src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/HomeController.java, src/main/java/coLaon/ClaonBack/version/repository/AppVersionRepository.java, src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
=> feat: find home posts

src/main/java/coLaon/ClaonBack/config/JwtAuthenticationEntryPoint.java, src/main/java/coLaon/ClaonBack/config/JwtAuthenticationFilter.java, src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
resolves None
fix bean create exception in jwt authentication filter
=> fix: fix bean create exception in jwt authentication filter

src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java
resolves None
change column name in sector info table about postgresql issue
=> fix: change column name in sector info table about postgresql issue

src/main/java/coLaon/ClaonBack/center/dto/SectorInfoResponseDto.java
resolves None
fix bug null point exception in sector info response dto
=> fix: fix bug null point exception in sector info response dto

src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java, src/main/java/coLaon/ClaonBack/user/repository/LaonRepositorySupport.java, src/main/java/coLaon/ClaonBack/user/service/LaonService.java, src/test/java/coLaon/ClaonBack/repository/LaonRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
resolves #245 
except block relation when read laon list
=> refac: except block relation when read laon list

src/main/java/coLaon/ClaonBack/center/repository/CenterRepositorySupport.java, src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
resolves #208 
feat: implement search center for new setting
- feat: implement search center for new setting
- refactor : remove search center in my around because of changing plan
=> feat: implement search center for new setting

src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
resolves None
modify cors configuration for cookie
=> refac: modify cors configuration for cookie

src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java, src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
resolves None
refactor cors option in security config
=> refac: refactor cors option in security config

src/main/java/coLaon/ClaonBack/common/utils/CookieUtil.java, src/main/java/coLaon/ClaonBack/common/utils/HeaderUtil.java, src/main/java/coLaon/ClaonBack/config/JwtAuthenticationFilter.java, src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java, src/main/java/coLaon/ClaonBack/user/web/AuthController.java
resolves #255 
change token location cookie to header
=> refac: change token location cookie to header

src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
resolves None
add exposed header for reponse header
=> feat: add exposed header for reponse header

src/main/java/coLaon/ClaonBack/storage/web/StorageController.java
resolves None
change request parameter to request part for image upload
=> fix: change request parameter to request part for image upload

src/main/java/coLaon/ClaonBack/center/domain/Center.java, src/main/java/coLaon/ClaonBack/post/dto/CenterClimbingHistoryResponseDto.java, src/main/java/coLaon/ClaonBack/post/dto/PostThumbnailResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/CenterPreviewResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/IndividualUserResponseDto.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #262 
modify individual page and mypage
=> refac: modify individual page and mypage

src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java, src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java, src/main/java/coLaon/ClaonBack/user/dto/CenterClimbingHistoryResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/ClimbingHistoryResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/HoldInfoResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/IndividualUserResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/PostThumbnailResponseDto.java, src/main/java/coLaon/ClaonBack/user/service/PostPort.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #265 
remove cyclic dependency between user and post module
=> refac: remove cyclic dependency between user and post module

src/main/java/coLaon/ClaonBack/post/infra/PostContentsUploader.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java
resolves #269 
post contents uploader
=> feat: post contents uploader

src/main/java/coLaon/ClaonBack/config/JwtAuthenticationFilter.java
resolves #283 
change jwt filter genericfileterbean to onceperrequestfilter
=> fix: change jwt filter genericfileterbean to onceperrequestfilter

src/main/resources/application-prod.yml
resolves None
add apache config for https
=> feat: add apache config for https

src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
resolves None
fix authenticationprincipal not visible in swagger
=> fix: fix authenticationprincipal not visible in swagger

src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
resolves None
modify to include headers in swagger
=> fix: modify to include headers in swagger

src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java, src/main/java/coLaon/ClaonBack/user/dto/UserModifyRequestDto.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java
resolves None
change arm reach and height to be null-safe
=> fix: change arm reach and height to be null-safe

src/main/java/coLaon/ClaonBack/common/domain/SwaggerPageable.java, src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
resolves None
change pageable to custom class for swagger
=> refac: change pageable to custom class for swagger

src/main/java/coLaon/ClaonBack/common/utils/S3Util.java, src/main/java/coLaon/ClaonBack/user/infra/ProfileImageManager.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java
resolves #259 
implement delete for profile image
- feat: implement delete function for profile image using user's profile image url
- refactor: modify module name to ProfileImageManager
=> feat: implement delete for profile image (#259)

src/main/java/coLaon/ClaonBack/common/domain/PaginationFactory.java
resolves None
refactor page number of pagination
=> refac: refactor page number of pagination

src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/notice/web/NoticeController.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/main/java/coLaon/ClaonBack/user/dto/SignInRequestDto.java, src/main/java/coLaon/ClaonBack/user/web/AuthController.java, src/main/java/coLaon/ClaonBack/user/web/LaonController.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java
resolves None
fix bug about all controller
=> fix: fix bug about all controller

src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java, src/main/java/coLaon/ClaonBack/user/dto/TestSignInRequestDto.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/AuthController.java
resolves None
return token for test
=> feat: return token for test

src/main/java/coLaon/ClaonBack/user/dto/TestSignInRequestDto.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java
resolves None
fix bug about jackson and lombok
=> fix: fix bug about jackson and lombok

.github/workflows/cd.yml
resolves None
add cd in github actions
=> feat: add cd in github actions

src/main/java/coLaon/ClaonBack/common/utils/S3Util.java, src/main/java/coLaon/ClaonBack/common/validator/IsExistUrlValidator.java, src/main/java/coLaon/ClaonBack/post/dto/PostContentsUrlDto.java, src/main/java/coLaon/ClaonBack/post/infra/PostContentsImageManager.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/main/java/coLaon/ClaonBack/user/infra/ProfileImageManager.java
resolves #299 
- implement delete s3 image for post contents using key
=> feat: implement delete s3 image for post contents using image path

src/main/java/coLaon/ClaonBack/post/domain/Post.java, src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java, src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java, src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java, src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #302 
fix bug about order of post climbing histories
=> fix: fix bug about order of post climbing histories

src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java, src/main/java/coLaon/ClaonBack/user/dto/CenterClimbingHistoryResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/UserCenterPreviewResponseDto.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #303 
fix naming collapse CenterPreviewResponseDto
=> refac: fix naming collapse CenterPreviewResponseDto

src/main/java/coLaon/ClaonBack/user/service/LaonService.java, src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
resolves #292 
validate laon user is blocked to create laon
=> refac: validate laon user is blocked to create laon

src/main/java/coLaon/ClaonBack/user/dto/UserDetailResponseDto.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #309 
refactor response dto of retrieve me api
=> refac: refactor response dto of retrieve me api

src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java, src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves #319 
add is owner to post detail dto
=> refac: add is owner to post detail dto

src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java, src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java, src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
resolves #320 
refactor dto of find all parent comment api
=> refac: refactor dto of find all parent comment api

src/main/java/coLaon/ClaonBack/post/dto/ChildCommentResponseDto.java, src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
resolves #320 
add is owner in child comment response dto
- add is owner in child comment response dto
- solve n+1 problem in find child comment
=> refac: add is owner in child comment response dto

src/main/java/coLaon/ClaonBack/center/dto/CenterDetailResponseDto.java, src/main/java/coLaon/ClaonBack/center/dto/CenterHoldInfoResponseDto.java, src/main/java/coLaon/ClaonBack/center/dto/CenterResponseDto.java, src/main/java/coLaon/ClaonBack/center/service/CenterService.java, src/main/java/coLaon/ClaonBack/center/service/CenterToUserAdapter.java, src/main/java/coLaon/ClaonBack/center/web/CenterController.java, src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java, src/main/java/coLaon/ClaonBack/user/dto/HistoryByCenterFindResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/HistoryGroupByMonthDto.java, src/main/java/coLaon/ClaonBack/user/service/CenterPort.java, src/main/java/coLaon/ClaonBack/user/service/PostPort.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java, src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #315 
- feat: implement find history by center 
- test: implement test code success case for find history by center
- fix: modify naming conflict for HoldInfoResponseDto file in both center and user package.
=> feat: implement find history by center (#315)

src/main/java/coLaon/ClaonBack/common/utils/JwtUtil.java
resolves None
fix bug about reissue refresh token
=> fix: fix bug about reissue refresh token

src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/web/PostController.java
=> fix: /posts/user/{nickname}/center/{centerId} url fix

src/main/java/coLaon/ClaonBack/post/web/PostController.java
resolves None
fix bug of post controller about endpoint collision
=> fix: fix bug of post controller about endpoint collision

src/main/java/coLaon/ClaonBack/post/repository/ClimbingHistoryRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java, src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java, src/main/java/coLaon/ClaonBack/user/dto/CenterInfoResponseDto.java, src/main/java/coLaon/ClaonBack/user/dto/HistoryByDateFindResponseDto.java, src/main/java/coLaon/ClaonBack/user/service/PostPort.java, src/main/java/coLaon/ClaonBack/user/service/UserService.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java, src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java, src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
resolves #316 
feat : implement find history method by center and date(year, month)
test : implement test code for above feature method
refac : modify find history by specific center because of considering all users
=> feat: implement find history method by center and date (#316)

src/main/java/coLaon/ClaonBack/post/service/PostService.java
resolves None
owner check in find post
=> fix: owner check in find post

src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java, src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java, src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java, src/main/java/coLaon/ClaonBack/post/service/PostService.java, src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java, src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
resolves None
add private and block check of post, post like, and post comment
=> fix: add private and block check of post, post like, and post comment

src/main/java/coLaon/ClaonBack/common/utils/RefreshTokenUtil.java, src/main/java/coLaon/ClaonBack/user/web/UserController.java
resolves None
fix bug about redis template delete key
=> fix: fix bug about redis template delete key

src/main/java/coLaon/ClaonBack/user/repository/UserRepositorySupport.java
resolves None
refactor search user to exclude not sign up user
=> refac: refactor search user to exclude not sign up user

.github/workflows/ci.yml, README.md, build.gradle, codecov.yml
resolves #333 
- construct so that code coverage can be measured when performing a pull request
=> feat: construct codecov (#333)

.gitignore, src/main/java/coLaon/ClaonBack/config/InterceptorConfig.java, src/main/java/coLaon/ClaonBack/config/TraceIdInterceptor.java, src/main/resources/logback-spring.xml
resolves #332
spring-starter에 내장된 Logback과 MDC 를 활용하여 로거 설정을 하였습니다. 
- traceId interceptor를 추가해서 요청 별로 트레이스 id를 부여하도록 하였습니다. 
- 로그 파일에 로그를 기록하도록 하였습니다. 이 때 RollingFileAppender를 활용해서 로그파일이 특정 용량 이상 되면 새 파일에 기록하도록 설정하였습니다. [참조](https://logback.qos.ch/manual/appenders.html)
=> feat: 로거 도입

src/main/java/coLaon/ClaonBack/config/RequestLoggingFilterConfig.java, src/main/java/coLaon/ClaonBack/config/TraceIdInterceptor.java, src/main/resources/application-prod.yml, src/main/resources/logback-spring.xml
resolves #332 
add info log in interceptor
=> feat: add info log in interceptor

src/main/java/coLaon/ClaonBack/post/web/PostController.java
resolves None
refactor delete post contents from body to header
=> refac: refactor delete post contents from body to header

src/main/java/coLaon/ClaonBack/config/CustomServletWrappingFilter.java, src/main/java/coLaon/ClaonBack/config/TraceIdInterceptor.java
resolves None
move logging interceptor to filter
=> refac: move logging interceptor to filter

src/main/java/coLaon/ClaonBack/notice/dto/NoticeResponseDto.java, src/test/java/coLaon/ClaonBack/service/NoticeServiceTest.java
resolves None
refactor notice response dto
=> refac: refactor notice response dto

src/main/java/coLaon/ClaonBack/config/CustomServletWrappingFilter.java
resolves None
fix null point exception in custom servlet wrapping filter
=> fix: fix null point exception in custom servlet wrapping filter

src/main/java/coLaon/ClaonBack/post/domain/ClimbingHistory.java, src/main/java/coLaon/ClaonBack/post/domain/PostComment.java
resolves None
refactor post comment and climbing history foreign key
=> refac: refactor post comment and climbing history foreign key

src/main/java/coLaon/ClaonBack/center/domain/CenterReport.java, src/main/java/coLaon/ClaonBack/post/domain/PostReport.java
resolves None
fix bug about foreign key constraints when delete user
=> fix: fix bug about foreign key constraints when delete user

src/main/java/coLaon/ClaonBack/post/domain/PostReport.java, src/main/resources/application-local.yml
=> fix: fix cascaded post delete when post report is deleted
